--CREATE SCHEMA SC DEFAULT CHARACTER SET utf8;
CREATE TABLE USERS( SYS_ID INTEGER PRIMARY KEY , LOGIN VARCHAR(20) NOT NULL, PASSWORD VARCHAR(300) NOT NULL, EMAIL VARCHAR(30) NOT NULL);
CREATE UNIQUE INDEX "users_LOGIN_uindex" ON USERS (LOGIN);
CREATE UNIQUE INDEX "users_SYS_ID_uindex" ON USERS (SYS_ID);