security:
  oauth2:
    client:
      clientId: 1795801387331791
      clientSecret: 28ab883cda2d6ffdbe92d719aab4fe64
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.security: DEBUG

spring:
  resources:
    chain:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver

hibernate:
  dialect: org.hibernate.dialect.Oracle10gDialect

oracle:
  login: s172752
  password: lkw664
  url: jdbc:oracle:thin:@localhost:1521:orbis
